### ISSUE TITLE
Allow to use gallery without Intent.CATEGORY_OPENABLE

### ISSUE THREAD

**Issue by tobibo** [miguelbcr/RxPaparazzo#48]
Hi there,

great work on the library guys. I ran into an issue though where would like to access images from my photos.google.com linked to my android account. They appear in the documents intent but just not with this library.

As i understand this does not work because you add the flag Intent.CATEGORY_OPENABLE in PickImages.java

`

        private Intent getFileChooserIntent() {
                Intent intent = new Intent();
                intent.setType("image/*");
        
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT) {
                    intent.setAction(Intent.ACTION_GET_CONTENT);
                } else {
                    intent.setAction(Intent.ACTION_OPEN_DOCUMENT);
                    intent.addCategory(Intent.CATEGORY_OPENABLE);
                }
        
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                    intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
                }
        
                return intent;
            }

`

Is this limitation there for a reason? Could the feature be added to allow fetching documents from sources for instance http:// ?

Thanks
Tobias

**Comment by miguelbcr** [comment]
Hi @tobibo ,

I was trying it but I'm not able to see that option when I pick an image in spite of install Google Photos as you can see at this [snapshot](http://puu.sh/rrFQ0/4ca08d303e.png)

Could you show me what appears to you?

**Comment by tobibo** [comment]
Oh ok, i was using a different library which is using the intent like so
`
        Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.setType("image/*");
`

and it was showing google photos, looks similar to what you do in the if statement above 
`
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT) {
`

**Comment by miguelbcr** [comment]
ok, thanks,  now it appears forcing `Intent.ACTION_GET_CONTENT`, and it works fine, but I have a problem, if I put `Intent.ACTION_GET_CONTENT` doesn't appear Gdrive option, which appear using `Intent.ACTION_OPEN_DOCUMENT`.

So I have to think how to address it, maybe with another config option...

**Comment by tobibo** [comment]
It this library, unfortunatelly it doesn't work so well with rxjava and some other things are nt quite right.
https://github.com/jkwiecien/EasyImage/blob/master/library/src/main/java/pl/aprilapps/easyphotopicker/EasyImage.java

**Comment by tobibo** [comment]
Ah ok, I didn't realise that. I have a think about it myself.

**Comment by tobibo** [comment]
For me it actually shows drive as well as other options like dropbox and onedrive, just tested it on a galaxy s6 running 6.0.1, could be platform/manufactur specific

**Comment by miguelbcr** [comment]
Yeah, it could be, I've tested it on Galaxy S3 4.4 and only appears Google Photos and Gallery with `Intent.ACTION_GET_CONTENT` and Documents, Recents, Downloads, Images, Gdrive, SD card with `ntent.ACTION_OPEN_DOCUMENT`

So, maybe finally I'll add an extra config option o choose which intent to use.

**Comment by miguelbcr** [comment]
Related commit: 9011d41fa147d575c2097fff9c367ce2858d0dfc

Finally I've decided to use `intent.setAction(Intent.ACTION_GET_CONTENT);` for all.

I've released [0.3.0 version](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.3.0) . Try it out and let me know if it works fine.

I've realized that with Google Photo I can't pick multiples images in spite of being able to select several pics, so only the first one is proccessed. It is because Google photo doesn't return all file paths, as far as I know.  Nevertheless, for example Google Drive works fine with multiple images.

**Comment by tobibo** [comment]
Thanks that was very quick, i have a look soon.

**Comment by tobibo** [comment]
Looks good! Great job!

**Comment by tobibo** [comment]
I actually just notice when i try to get a photo from google photos i get this exception:

Permission Denial: reading com.google.android.apps.photos.contentprovider.MediaContentProvider

There is a fix explained here, i am not exactly sure where the image gets copied in the library. Any thoughts?

**Comment by miguelbcr** [comment]
I managed to reproduce the error, I think it is because of [temporary read permissions](http://stackoverflow.com/a/31274622/5502014).

In the library the image gets copied in [DownloadImage class](https://github.com/miguelbcr/RxPaparazzo/blob/3bddf402088db7c3d3183e0838a59eab8fc1714f/rx_paparazzo/src/main/java/com/fuck_boilerplate/rx_paparazzo/interactors/DownloadImage.java) within [GetPath class](https://github.com/miguelbcr/RxPaparazzo/blob/a2fe3f26737eb0fc9c9400e5aa88431c050e8327/rx_paparazzo/src/main/java/com/fuck_boilerplate/rx_paparazzo/interactors/GetPath.java) which is called after [PickImage class](https://github.com/miguelbcr/RxPaparazzo/blob/a2fe3f26737eb0fc9c9400e5aa88431c050e8327/rx_paparazzo/src/main/java/com/fuck_boilerplate/rx_paparazzo/interactors/PickImage.java) is finished, so I think the temporary permissions is no longer available when the image is downloaded.

I'll take a look to this, thanks.

**Comment by miguelbcr** [comment]
Hi @tobibo ,
I've released [version 0.3.1](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.3.1) which solves the problem with temporary permissions.

Try it out and let me know if it solves your problem.
Thanks.

**Comment by tobibo** [comment]
Great job @miguelbcr, it works perfect. Thanks for the quick turn around.
