### ISSUE TITLE
how to multiple choice

### ISSUE THREAD

**Issue by namezhouyu** [miguelbcr/RxPaparazzo#52]

**Comment by miguelbcr** [comment]
Hi @namezhouyu ,

you shold call to **takeImages()**:

```java
RxPaparazzo.takeImages(activityOrFragment)
        .usingGallery()
        .subscribe(response -> {
            if (response.resultCode() != RESULT_OK) {
                response.targetUI().showUserCanceled();
                return;
            }

            if (response.data().size() == 1) response.targetUI().loadImage(response.data().get(0));
            else response.targetUI().loadImages(response.data());
        });
```

but keep in mind that prior to API 18, only one image will be retrieved.

**Comment by namezhouyu** [comment]
Thinks for your answer, but i can not select multiple images ,the "response.data().size()" always be 1.
Test in samsung SM-N910K (api 23).

**Comment by miguelbcr** [comment]
Sorry, I forgot to tell you that you have to click by a long press the first image and then you will be able to select other ones by clicking. This is he normal Android behaviour. I don't know if you were aware of this, otherwise I don't know what is wrong. Have you been able to select several images with other apps, such as the native Gallery app?

**Comment by namezhouyu** [comment]
Native Gallery is okay, but the demo can not.Maybe the phone system is not google native android.
Anyway, thinks.

**Comment by miguelbcr** [comment]
Thats very weird, because RxPaparazzo delegates the pick images action to third parties apps like native Gallery, among others, so maybe it is related with the app you are trying to pick up the images. I remember, for example, that Google Photos or Google Drive app, I can't remember exactly, only could pick up a single image in spite of call to takeImages().

**Comment by namezhouyu** [comment]
Thinks

**Comment by miguelbcr** [comment]
thinks or thanks? :)

**Comment by namezhouyu** [comment]
sorry,thanks  haha
