### ISSUE TITLE
Resizing images bug.

### ISSUE THREAD

**Issue by ramanbranavitski** [miguelbcr/RxPaparazzo#76]
Hi @miguelbcr. I've found a bug in your library. According to the documentation 

> inSampleSize
> added in API level 1
> int inSampleSize
> If set to a value > 1, requests the decoder to subsample the original image, returning a smaller image to save memory. The sample size is the number of pixels in either dimension that correspond to a single pixel in the decoded bitmap. For example, inSampleSize == 4 returns an image that is 1/4 the width/height of the original, and 1/16 the number of pixels. Any value <= 1 is treated the same as 1. Note: the decoder uses a final value based on powers of 2, any other value will be rounded down to the nearest power of 2.

In your [calculateInSampleSize](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/interactors/ImageUtils.java#L438) method you need to double `inSampleSize` variable instead of increasing its value. In my case this value was 3 and I need to make my bitmap 3x smaller, but when I use `inSampleSize = 3`, system makes it only 2x smaller. I'll create a hot fix and hope you'll update your library.

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski for reporting it!

Right now I can't remember clearly why about that implementation, but I think it was because you, as user, would prefer get the previous `inSampleSize` instead of exceed it and get a poor quality image accordingly.

Anyway the best would be compare the current output with other implementations such us yours and, for instance, [the google's one](https://github.com/googlesamples/android-DisplayingBitmaps/blob/master/Application/src/main/java/com/example/android/displayingbitmaps/util/ImageResizer.java#L231), for differents inputs (original and desire image size)

**Comment by ramanbranavitski** [comment]
If so, no one of `ImageSize` make any science. For example I want to use `CustomMaxSize` and want my image to be no more then 1000px. But using your implementation it could be. Even google recommend to double `isSampleSize` when you calculate it. Look [Loading Large Bitmaps Efficiently](https://developer.android.com/topic/performance/graphics/load-bitmap.html)

**Comment by miguelbcr** [comment]
Yeah, maybe you are right, but I'd  like to make tests before changing it and compare the different outputs, just to clear doubts

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski ,
I did some tests, this is the output ([Google1](https://github.com/googlesamples/android-DisplayingBitmaps/blob/master/Application/src/main/java/com/example/android/displayingbitmaps/util/ImageResizer.java#L231) and [Google2](https://developer.android.com/topic/performance/graphics/load-bitmap.html)):
```
Test 0) width X height: original= 1000x1000 required= 1000x1000
   inSampleSize with RxPaparazzo ++ = 1
   inSampleSize with RxPaparazzo *2 = 1
   inSampleSize with Google1 = 1
   inSampleSize with Google2 = 1
Test 1) width X height: original= 1000x1000 required= 100x100
   inSampleSize with RxPaparazzo ++ = 10
   inSampleSize with RxPaparazzo *2 = 10
   inSampleSize with Google1 = 64
   inSampleSize with Google2 = 8
Test 2) width X height: original= 100x1000 required= 100x100
   inSampleSize with RxPaparazzo ++ = 3
   inSampleSize with RxPaparazzo *2 = 4
   inSampleSize with Google1 = 8
   inSampleSize with Google2 = 1
Test 3) width X height: original= 1000x100 required= 100x100
   inSampleSize with RxPaparazzo ++ = 3
   inSampleSize with RxPaparazzo *2 = 4
   inSampleSize with Google1 = 8
   inSampleSize with Google2 = 1
Test 4) width X height: original= 3456x1234 required= 100x100
   inSampleSize with RxPaparazzo ++ = 15
   inSampleSize with RxPaparazzo *2 = 24
   inSampleSize with Google1 = 256
   inSampleSize with Google2 = 8
Test 5) width X height: original= 100x100 required= 1000x1000
   inSampleSize with RxPaparazzo ++ = 1
   inSampleSize with RxPaparazzo *2 = 1
   inSampleSize with Google1 = 1
   inSampleSize with Google2 = 1
Test 6) width X height: original= 10x10 required= 3x3
   inSampleSize with RxPaparazzo ++ = 3
   inSampleSize with RxPaparazzo *2 = 3
   inSampleSize with Google1 = 8
   inSampleSize with Google2 = 2
Test 7) width X height: original= 10x10 required= 2x2
   inSampleSize with RxPaparazzo ++ = 5
   inSampleSize with RxPaparazzo *2 = 5
   inSampleSize with Google1 = 16
   inSampleSize with Google2 = 4
``` 

Since `inSampleSize` is a power of 2 it will take the values 1, 2, 4, 8, 16, 32, 64, ... (any other value will be rounded down to the nearest power of 2.)

I think your case is similar to `Test 2, 3 or 6` where it is preferable get the rounded down in order to preserve the most image quality as posible for your target dimensions.

Another special case is `Test 4` where the result for `RxPaparazzo ++ = 15` is the same for `Google2 = 8` (because 15 rounded down is 8) and I think `RxPaparazzo *2 = 24` is excessive (rounded down is 16). By the way I think `Google1 = 256` is a bad implementation...

So according to these tests I'm not sure that change `inSampleSize++` to `inSampleSize*=2` is a good solution. Maybe you could change the custom size in order to get a smaller image, I don't know....

Anyway I'd like to test your particular case in order to see the output for those algorithms.
Could you please provide the original dimensions and the required ones?

Thanks!

**Comment by ramanbranavitski** [comment]
Hi @miguelbcr. I've tested with an image 2448x3264 and use CustomMaxSize with it's default value = 1024.

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski ,
this is the output:
```
Test 8) width X height: original= 2448x3264 required= 768x1024
   inSampleSize with RxPaparazzo ++ = 3
   inSampleSize with RxPaparazzo *2 = 3
   inSampleSize with Google1 = 8
   inSampleSize with Google2 = 2
``` 
The `required` dimensions from a custom size are calculated [here](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/interactors/ScaledImageDimensions.java#L72)

The doc in [CustomMaxSize class](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/entities/size/CustomMaxSize.java#L4-L5) says:
> Scale source image proportionally. Max size of new image will be approximately equal to maxImageSize.

So I think the implementation is good. It's preferable not scale down in excess and preserve  the nearest down power of 2.

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski , something new? 
I think I'll close the issue and PR's ...
