### ISSUE TITLE
Activity restart when capture image

### ISSUE THREAD

**Issue by zabi90** [miguelbcr/RxPaparazzo#85]
Hi,
I like this library and i'm using first time this. I'm facing issue that is, when i capture image from camera in some device it's restart the activity and the image is not shown.

**Comment by miguelbcr** [comment]
Hi @zabi90 !
are you using the sample app or your own app?
Try to reproduce that on the sample app and gather some information, because right now I can imagine the cause apart from that the System closes the activity according to its policy (low memory, ...)

**Comment by zabi90** [comment]
Yes it is due to low memory. Now it's working fine. I'll try to test your
sample app.

**Comment by zabi90** [comment]
@miguelbcr Is there any way i can save the file path in activity saveInstance bundle so that i can restore it when activity restart.

**Comment by miguelbcr** [comment]
Currently not because it generates a file name automatically based on timestamp, but it would be an interesting feature to know the filename or passing it to the lib before launching it.

Right now I have no time to do that, but you are welcome to make a PR if you are confident with the code.

Btw, what Android version has the devices were failing?

**Comment by ezlo-aleksp** [comment]
I have got the same issue on Samsung A3  5.01

**Comment by dimanych** [comment]
Xiaomi Redmi 4 pro(Android 6.0.1) has the same issue
Fix:
For correct working with that use new `Activity` from `response.targetUI()` after taking picture.
